apiVersion: v1
kind: Pod
metadata:
   name: cart-app-pod
   namespace: aaron-Namespace
spec:
   containers:
   - name: test-container
     image: aarondani/sre-test-image:1.0
     ports:
     - containerPort: 3015
